name: 'install-juliaup'
description: 'Install Juliaup, add it to the PATH, and use it to install Julia'
author: 'julia-actions organization, contributors'
inputs:
  channel:
    description: 'The Juliaup channel to install (and set as the default channel).'
    required: true
  internal-juliaup-version:
    description: '[private internal]. The Juliaup version to install. This is not part of the public API of this action.'
    required: false
    default: '1.18.2' # Update this value whenever a new release of Juliaup is made.
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'download'
  color: 'green'
