name: 'install-juliaup'
description: 'Install Juliaup, add it to the PATH, and use it to install Julia'
author: 'julia-actions organization, contributors'
inputs:
  channel:
    description: 'The Juliaup channel to install (and set as the default channel).'
    required: true
  token:
    description: 'GitHub token to use when contacting the GitHub API to fetch the list of Juliaup versions'
    required: false
    default: ${{ github.token }}
  juliaup-version:
    description: 'The Juliaup version to install. Defaults to latest-v1, which expands to the latest available 1.x.y version of Juliaup.'
    required: false
    default: 'latest-v1'
runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: 'download'
  color: 'green'
